### ISSUE TITLE
Add internal variables

### ISSUE THREAD

**Issue by effectfully** [effectfully/tiny-lang#14]
Variable assignments like

```
a = ...
b = ...
```

are required downstream. Variables are immutable. So basically we need something like Haskell's `let`-expressions.

**Comment by effectfully** [comment]
Partially done in 3117e9bfac5496cb6605502bb03283ee9897d23e. Generation, parsing and proper printing are missing currently.

**Comment by kwxm** [comment]
There's a difficulty with generators because now we have to produce variables with fresh `Unique`s when we generate a random `let`-expression, so we apparently have to propagate state through generators.

I spent a while experimenting with `SupplyT`, but it wasn't ideal.  I defined `type GenU = SupplyT Gen` and made lots of generators of type `GenU`, but then I had to have `lift` all over the place.  I also had trouble with some of QuickCheck's generator combinators.  For example we can use `frequency :: [(Int, Gen a)] -> Gen a` to combine a bunch of generators with different probabilities.  I had a bunch of `GenU`s and wanted to use `frequency`, but I had trouble with this:  you need to lift it to something of type `[(Int, GenU a)] -> GenU a`, but I couldn't see any easy way to do this.  I eventually had to copy the source of the original `frequency` function and stick a `lift` in the middle of it, and I had to do something similar wwith some of the other combinators.  Do you have any suggestions of an easier way to do this?

I also tried `QuickCheck.GenT` (http://hackage.haskell.org/package/QuickCheck-GenT-0.2.0/docs/QuickCheck-GenT.html), which lets you use `Supply` as the inner monad.  I was able to define generators of type `GenT (Supply Unique) Expr` for example, which gives you random things of type `Supply Unique Expr`: you then have to use `evalSupply` to evaluate these with an initial supply to generate actual random expressions.  This is a bit better, but there's still some monad transformer stuff which I think has to be exposed in the interface, so it's still more complicated than before.

However, it turns out that there's a purely functional way to do all this.  The problem with using a linear supply of `Unique`s is that if you're generating something like `e1 * e2` you have to generate `e1` and then somehow get back the current state of the uniques to use in `e1`.  But what you can do is have an infinite _tree_ of `Unique`s and use one branch of that to generate `e1` and the other one to generate `e2`.  I got this idea from https://andreaspk.github.io/posts/2019-06-17-Taking%20a%20look%20at%20GHC%20creates%20unique%20Ids.html, which I think is based on "On generating unique names" by Lennart Augustsson and others, although I can't access that. Interestingly, it looks as if the way it's done in GHC is what causes GHC to be non-deterministic, something that's been mentioned as being problematic if we want to convince someone that a particular PLC term was compiled from a particular bit of source code.

The GHC details are moderately complicated, but the basic idea is easy to implement:

```
data Uniques = Uniques Unique Uniques Uniques      -- Hmmm...

mkUniques :: Integer -> Uniques
mkUniques n = Uniques (Unique n) (mkUniques (2*n+1)) (mkUniques (2*n+2))
```
If you call `mkUniques` 0 then you get a binary tree which contains all of the non-negative numbers exactly once, and you can pass this as an extra parameter to every generator (well, really you don't start at 0 but just past the highest `Unique` that you've already got; that doesn't make any difference though).

This seems a lot cleaner than the monad transformer versions, but there is a problem.  Things at depth n in the AST will have uniques of the order of 2^n, so there's a danger that they won't fit into an `Int` if the AST's deep; we can fix this by using `Integer` in `Unique` instead of `Int`.  Also, we won't always need any fresh variables in a new subterm, and this will lead to us discarding an entire subtree of the infinite tree of `Uniques`, and we'll typically end up with terms with quite large and apparently random uniques in them rather than everything being neatly numbered 0,1,2,3,... . This might be a price worth paying to avoid the monad transformers.

**Comment by effectfully** [comment]
> For example we can use `frequency :: [(Int, Gen a)] -> Gen a` to combine a bunch of generators with different probabilities. 

I'm not quite sure yet, but I think this a problem of `QuickCheck` rather than our problem. I think, the type signature should be `frequency :: [(Int, a)] -> Gen a`, which is more generic (and the current `frequency` should be a derivative). Looking at the implementation, we see that defining `frequencyT` in terms of `frequency` is possible:

```haskell
frequencyT :: (MonadTrans t, Monad (t Gen)) => [(Int, t Gen a)] -> t Gen a
frequencyT = join . lift . frequency . map (fmap pure)
```

Here we wrap each generator from a list in a dummy generator that always returns the original generator, use `frequency` to choose an element from the resulting list and as a side effect (that I think just shouldn't be there) this runs the dummy generator and gives us back a generator from the original list wrapped into `Gen` and then we collapse the two layers of generators into a single one.

Other similar functions also can be misused in the same way (but perhaps not all of them).

> I also tried `QuickCheck.GenT` (http://hackage.haskell.org/package/QuickCheck-GenT-0.2.0/docs/QuickCheck-GenT.html), which lets you use `Supply` as the inner monad.

This makes perfect sense to me. I don't know why `QuickCheck` itself defines `Gen` rather than `GenT`.

> This is a bit better, but there's still some monad transformer stuff which I think has to be exposed in the interface, so it's still more complicated than before.

How bad is that? Could you show the branch?

> Also, we won't always need any fresh variables in a new subterm, and this will lead to us discarding an entire subtree of the infinite tree of `Uniques`, and we'll typically end up with terms with quite large and apparently random uniques in them rather than everything being neatly numbered 0,1,2,3,... . This might be a price worth paying to avoid the monad transformers.

I think it's a huge price. It is very important for generated terms to be readable, because if something fails, we want to get a comprehensible counterexample. We can rename that counterexample afterwards, but it's a complication. I'd also prefer not to introduce a source of non-determinism.

**Comment by kwxm** [comment]
> >  This is a bit better, but there's still some monad transformer stuff which I think has to be exposed in the interface, so it's still more complicated than before.

> How bad is that? Could you show the branch?

I was experimenting with a really smal language just to see how it worked, so I don't have a full version for the main language.  It shouldn't take too long to make one though, so I'll do that.  It's possible that that may reveal some unexpected problems.

>   I think it's a huge price. It is very important for generated terms to be readable, because if something fails, we want to get a comprehensible counterexample. We can rename that counterexample afterwards, but it's a complication. I'd also prefer not to introduce a source of non-determinism.

Actually the results don't look too bad, and it is in fact completely deterministic.  The GHC version's a lot more complicated (including FFI stuff involving C) and I think they introduce nondeterminism to speed things up because this is something that gets used a lot.  

I'll make branches with both a GenT version and a pure version so you can have a look.

(Meanwhile I've discovered that the parser is unbelievably slow on some (not very big) examples, so I'm trying to work out what's causing that).

**Comment by effectfully** [comment]
> This makes perfect sense to me. I don't know why `QuickCheck` itself defines `Gen` rather than `GenT`.

Probably the answer is "for hysterical raisins" and "for performance reasons". Not really satisfying to me.

We ended up with the `GenT` approach (in its `mtl` form). Done in #18.
